# Generated by Django 2.1.5 on 2021-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='img',
            field=models.ImageField(upload_to='fronend'),
        ),
    ]
